"""Add BattleHistory table and User battle stats

Revision ID: ce8fe3791051
Revises: 
Create Date: 2026-07-12 14:47:37.751508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8fe3791051'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_id'), 'battles', ['id'], unique=False)
    op.create_table('battle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_logs_id'), 'battle_logs', ['id'], unique=False)
    op.create_table('battle_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('damage_received', sa.Integer(), nullable=True),
    sa.Column('pokemon_used', sa.JSON(), nullable=False),
    sa.Column('moves_used', sa.JSON(), nullable=False),
    sa.Column('battle_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_statistics_id'), 'battle_statistics', ['id'], unique=False)
    op.create_table('battle_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('player_action', sa.JSON(), nullable=False),
    sa.Column('opponent_action', sa.JSON(), nullable=False),
    sa.Column('resulting_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_turns_id'), 'battle_turns', ['id'], unique=False)
    op.add_column('users', sa.Column('battles_played', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('win_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('favorite_pokemon', sa.String(), nullable=True))
    op.add_column('users', sa.Column('most_used_move', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avg_damage', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longest_battle_turns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longest_battle_turns')
    op.drop_column('users', 'avg_damage')
    op.drop_column('users', 'most_used_move')
    op.drop_column('users', 'favorite_pokemon')
    op.drop_column('users', 'win_rate')
    op.drop_column('users', 'losses')
    op.drop_column('users', 'wins')
    op.drop_column('users', 'battles_played')
    op.drop_index(op.f('ix_battle_turns_id'), table_name='battle_turns')
    op.drop_table('battle_turns')
    op.drop_index(op.f('ix_battle_statistics_id'), table_name='battle_statistics')
    op.drop_table('battle_statistics')
    op.drop_index(op.f('ix_battle_logs_id'), table_name='battle_logs')
    op.drop_table('battle_logs')
    op.drop_index(op.f('ix_battles_id'), table_name='battles')
    op.drop_table('battles')
    # ### end Alembic commands ###
